namespace: documentdb-operator
replicaCount: 1

# DocumentDB version - global default for all components when individual tags are not set
# Priority: individual component tag > documentDbVersion > Chart.appVersion
# Defaults to Chart.appVersion if not specified  
documentDbVersion: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "documentdb-operator"
  
image:
  documentdbk8soperator:
    repository: ghcr.io/hossain-rayhan/documentdb-kubernetes-operator/operator
    pullPolicy: Always
  sidecarinjector:
    repository: ghcr.io/hossain-rayhan/documentdb-kubernetes-operator/sidecar
    pullPolicy: Always
    
cloudnative-pg:
  namespaceOverride: cnpg-system
